---
title: "Censo da Educação em Rio grande - RS"
format: 
  dashboard: 
    orientation: columns
editor: visual
theme: lux
---

```{r}
#|warnings: false

library(getcensoeducacaodata)
library(tidyverse)
library(gt)

data_creches <- read.csv("data_creches.csv")

data_ef <- read.csv("data_ef.csv")

data_em <- read.csv("data_em.csv")

data_matriculas <- read.csv("data_matriculas.csv")

data_escolas_ger <- read.csv("data_escolas_geral.csv") %>%
  mutate(Porcentagem = round(Número/sum(Número) * 100, digits = 0))
  
```

# Sidebar {.sidebar}

```{r}
data_sidebar <- data.frame(
  Dados = c("Creches", "Escolas de Ensino Fundamental", "Escolas de Ensino Médio", "Matrículas")
) 

data_sidebar %>%
  gt(rowname_col = "Dados") %>%
  tab_header(
    title = "Esse Dashboard apresenta os microdados do Censo da Educação para o Município de Rio Grande - RS"
  ) 
  

```

# Estatísticas

## Column {.fill}

### Row

```{r data}
n_creches <- data_creches[2, 4]
  
n_ef <- data_ef[2,4]
  
n_em <- data_em[2,4]
  
```

```{r}
#| content: valuebox
#| title: "Número de Creches"
list(
  icon = "info-circle-fill",
  color = "success",
  value = n_creches
)

```

```{r}
#| content: valuebox
#| title: "Número de escolas de ensino fundamental"
list(
  icon = "info-circle-fill",
  color = "success",
  value = n_ef
)

```

```{r}
#| content: valuebox
#| title: "Número de escolas de ensino médio"
list(
  icon = "info-circle-fill",
  color = "success",
  value = n_em
)

```

### Row {.fill}

```{r}
data_matriculas %>%
  ggplot() +
    geom_line(aes(x = nu_ano_censo, y = total_matriculas_pre_escola)) +
    geom_point(aes(x = nu_ano_censo, y = total_matriculas_pre_escola)) +
    scale_y_continuous(limits = c(3000, 5250)) +
    scale_x_continuous(n.breaks = 12) +
    theme_bw() +
    labs(
      y = "Número de Matrículas na Pré Escola em Rio Grande", 
      x = "Ano"
    ) +
    theme(
      panel.border = element_blank(),
      panel.grid.minor = element_blank()
    )


```

```{r}
data_matriculas %>%
  ggplot() +
    geom_line(aes(x = nu_ano_censo, y = total_matriculas_medio)) +
    geom_point(aes(x = nu_ano_censo, y = total_matriculas_medio)) +
    scale_y_continuous(limits = c(4500, 7250)) +
    scale_x_continuous(n.breaks = 12) +
    theme_bw() +
    labs(
      y = "Número de Matrículas no Ensino Médio em Rio Grande", 
      x = "Ano"
    ) +
    theme(
      panel.border = element_blank(),
      panel.grid.minor = element_blank()
    )


```

```{r}
data_matriculas %>%
  ggplot() +
    geom_line(aes(x = nu_ano_censo, y = total_matriculas_medio)) +
    geom_point(aes(x = nu_ano_censo, y = total_matriculas_medio)) +
    scale_y_continuous(limits = c(4500, 7250)) +
    scale_x_continuous(n.breaks = 12) +
    theme_bw() +
    labs(
      y = "Número de Matrículas no Ensino Médio em Rio Grande", 
      x = "Ano"
    ) +
    theme(
      panel.border = element_blank(),
      panel.grid.minor = element_blank()
    )


```

### Row {height="30%"}

Os gráficos foram feitos a partir dos microdados do Censo Escolar, obtidos através do pacote do R "getcensoeducacaodata" (https://github.com/BaruqueRodrigues/getcensoeducacaodata). Os dados foram baixados para o ano de 2023.

# Dados

```{r}
data_matriculas %>%
  gt()

```
